// app/lib/placeholder-data.ts
import { Country, Player, Position } from '@/lib/definitions';

/**
 * Diccionario indexado de Selecciones Nacionales (Countries).
 * Clave: ID de la selección (slug de 3 caracteres).
 */
export const countriesData: Record<string, Country> = {
  bra: { id: 'bra', name: 'Brasil', flagUrl: '/flags/bra.svg', titlesCount: 5 },
  deu: { id: 'deu', name: 'Alemania', flagUrl: '/flags/deu.svg', titlesCount: 4 },
  ita: { id: 'ita', name: 'Italia', flagUrl: '/flags/ita.svg', titlesCount: 4 },
  arg: { id: 'arg', name: 'Argentina', flagUrl: '/flags/arg.svg', titlesCount: 3 },
  fra: { id: 'fra', name: 'Francia', flagUrl: '/flags/fra.svg', titlesCount: 2 },
  uru: { id: 'uru', name: 'Uruguay', flagUrl: '/flags/uru.svg', titlesCount: 2 },
  esp: { id: 'esp', name: 'España', flagUrl: '/flags/esp.svg', titlesCount: 1 },
  eng: { id: 'eng', name: 'Inglaterra', flagUrl: '/flags/eng.svg', titlesCount: 1 },

  // Finalistas y selecciones históricas
  nld: { id: 'nld', name: 'Países Bajos', flagUrl: '/flags/nld.svg', titlesCount: 0 },
  hrv: { id: 'hrv', name: 'Croacia', flagUrl: '/flags/hrv.svg', titlesCount: 0 },
  prt: { id: 'prt', name: 'Portugal', flagUrl: '/flags/prt.svg', titlesCount: 0 },
  mar: { id: 'mar', name: 'Marruecos', flagUrl: '/flags/mar.svg', titlesCount: 0 },
  bel: { id: 'bel', name: 'Bélgica', flagUrl: '/flags/bel.svg', titlesCount: 0 },
};

/**
 * Lista optimizada de Jugadores de Élite y de Leyenda.
 * Mapeados estrictamente mediante countryId.
 */
export const playersData: Player[] = [
  // --- ESPAÑA (esp) ---
  { id: 'p-casillas', name: 'Iker Casillas', shortName: 'Casillas', nickname: 'El Santo', countryId: 'esp', position: 'POR', otherPositions: [], rating: 93, worldCupEdition: 2010 },
  { id: 'p-rodri', name: 'Rodri Hernández', shortName: 'Rodri', nickname: 'El Faro', countryId: 'esp', position: 'MCD', otherPositions: ['MC', 'DFC'], rating: 91, worldCupEdition: 2022 },
  { id: 'p-iniesta', name: 'Andrés Iniesta', shortName: 'Iniesta', nickname: 'El Cerebro', countryId: 'esp', position: 'MC', otherPositions: ['MCO', 'EI'], rating: 94, worldCupEdition: 2010 },
  { id: 'p-yamal', name: 'Lamine Yamal', shortName: 'Lamine Yamal', nickname: 'El Prodigio', countryId: 'esp', position: 'ED', otherPositions: ['EI', 'DC'], rating: 86, worldCupEdition: 2026 },
  { id: 'p-pique', name: 'Gerard Piqué', shortName: 'Piqué', nickname: 'Piquenbauer', countryId: 'esp', position: 'DFC', otherPositions: [], rating: 87, worldCupEdition: 2010 },
  { id: 'p-xavi', name: 'Xavi Hernández', shortName: 'Xavi', nickname: 'La Computadora', countryId: 'esp', position: 'MC', otherPositions: ['MCO'], rating: 96, worldCupEdition: 2010 },
  { id: 'p-sergioramos', name: 'Sergio Ramos', shortName: 'Sergio Ramos', nickname: 'El Faraón de Camas', countryId: 'esp', position: 'DFC', otherPositions: ['LD'], rating: 96, worldCupEdition: 2010 },
  { id: 'p-puyol', name: 'Carles Puyol', shortName: 'Puyol', nickname: 'Tiburón', countryId: 'esp', position: 'DFC', otherPositions: ['LD', 'LI'], rating: 95, worldCupEdition: 2010 },
  { id: 'p-villa', name: 'David Villa', shortName: 'Villa', nickname: 'El Guaje', countryId: 'esp', position: 'DC', otherPositions: ['EI', 'ED'], rating: 95, worldCupEdition: 2010 },
  { id: 'p-torres', name: 'Fernando Torres', shortName: 'Torres', nickname: 'El Niño', countryId: 'esp', position: 'DC', otherPositions: [], rating: 93, worldCupEdition: 2010 },
  { id: 'p-raul', name: 'Raúl González', shortName: 'Raúl', nickname: 'El Ángel de Madrid', countryId: 'esp', position: 'DC', otherPositions: ['SD', 'MCO'], rating: 95, worldCupEdition: 2002 },
  { id: 'p-busquets', name: 'Sergio Busquets', shortName: 'Busquets', nickname: 'Busi', countryId: 'esp', position: 'MCD', otherPositions: ['MC'], rating: 94, worldCupEdition: 2010 },
  { id: 'p-alonso', name: 'Xabi Alonso', shortName: 'Xabi Alonso', nickname: 'El Maestro', countryId: 'esp', position: 'MC', otherPositions: ['MCD'], rating: 94, worldCupEdition: 2010 },
  { id: 'p-silva', name: 'David Silva', shortName: 'Silva', nickname: 'El Mago', countryId: 'esp', position: 'MCO', otherPositions: ['EI', 'ED', 'MC'], rating: 93, worldCupEdition: 2010 },
  { id: 'p-fabregas', name: 'Cesc Fàbregas', shortName: 'Fàbregas', nickname: 'El Arquitecto', countryId: 'esp', position: 'MC', otherPositions: ['MCO', 'DC'], rating: 91, worldCupEdition: 2010 },
  { id: 'p-alba', name: 'Jordi Alba', shortName: 'Jordi Alba', nickname: 'La Bala de L’Hospitalet', countryId: 'esp', position: 'LI', otherPositions: ['EI'], rating: 88, worldCupEdition: 2014 },
  { id: 'p-carvajal', name: 'Dani Carvajal', shortName: 'Carvajal', nickname: 'El Pitbull', countryId: 'esp', position: 'LD', otherPositions: ['CAD'], rating: 89, worldCupEdition: 2022 },
  { id: 'p-hierro', name: 'Fernando Hierro', shortName: 'Hierro', nickname: 'El Mariscal', countryId: 'esp', position: 'DFC', otherPositions: ['MCD', 'MC'], rating: 94, worldCupEdition: 2002 },
  { id: 'p-suarez-luis', name: 'Luis Suárez Miramontes', shortName: 'Luis Suárez', nickname: 'El Arquitecto de Oro', countryId: 'esp', position: 'MC', otherPositions: ['MCO'], rating: 95, worldCupEdition: 1962 },
  { id: 'p-pedri', name: 'Pedro González', shortName: 'Pedri', nickname: 'El Mago de Tegueste', countryId: 'esp', position: 'MC', otherPositions: ['MCO'], rating: 88, worldCupEdition: 2022 },

  // --- BRASIL (bra) ---
  { id: 'p-pele', name: 'Pelé', shortName: 'Pelé', nickname: 'O Rei', countryId: 'bra', position: 'DC', otherPositions: ['MCO', 'SD'], rating: 98, worldCupEdition: 1970 },
  { id: 'p-garrincha', name: 'Garrincha', shortName: 'Garrincha', nickname: 'A Alegria do Povo', countryId: 'bra', position: 'ED', otherPositions: ['DC'], rating: 97, worldCupEdition: 1962 },
  { id: 'p-jairzinho', name: 'Jairzinho', shortName: 'Jairzinho', nickname: 'O Furacão', countryId: 'bra', position: 'ED', otherPositions: ['DC', 'EI'], rating: 95, worldCupEdition: 1970 },
  { id: 'p-tostao', name: 'Tostão', shortName: 'Tostão', nickname: 'El Pelé Blanco', countryId: 'bra', position: 'DC', otherPositions: ['MCO', 'SD'], rating: 94, worldCupEdition: 1970 },
  { id: 'p-rivelino', name: 'Rivelino', shortName: 'Rivelino', nickname: 'Patada Atómica', countryId: 'bra', position: 'MCO', otherPositions: ['EI', 'MC'], rating: 95, worldCupEdition: 1970 },
  { id: 'p-romario', name: 'Romário', shortName: 'Romário', nickname: 'O Baixinho', countryId: 'bra', position: 'DC', otherPositions: [], rating: 96, worldCupEdition: 1994 },
  { id: 'p-bebeto', name: 'Bebeto', shortName: 'Bebeto', nickname: 'El Chorcecito', countryId: 'bra', position: 'DC', otherPositions: ['SD'], rating: 91, worldCupEdition: 1994 },
  { id: 'p-r9', name: 'Ronaldo Nazário', shortName: 'Ronaldo', nickname: 'O Fenômeno', countryId: 'bra', position: 'DC', otherPositions: [], rating: 97, worldCupEdition: 2002 },
  { id: 'p-rivaldo', name: 'Rivaldo', shortName: 'Rivaldo', nickname: 'El Zurdo de Oro', countryId: 'bra', position: 'MCO', otherPositions: ['SD', 'EI', 'DC'], rating: 95, worldCupEdition: 2002 },
  { id: 'p-ronaldinho', name: 'Ronaldinho Gaucho', shortName: 'Ronaldinho', nickname: 'Bruxo', countryId: 'bra', position: 'MCO', otherPositions: ['EI', 'SD'], rating: 97, worldCupEdition: 2002 },
  { id: 'p-kaka', name: 'Kaká', shortName: 'Kaká', nickname: 'Il Bambino d\'Oro', countryId: 'bra', position: 'MCO', otherPositions: ['SD'], rating: 94, worldCupEdition: 2006 },
  { id: 'p-cafu', name: 'Cafú', shortName: 'Cafú', nickname: 'O Trem de Dionísio', countryId: 'bra', position: 'LD', otherPositions: ['CAD'], rating: 94, worldCupEdition: 2002 },
  { id: 'p-robertocarlos', name: 'Roberto Carlos', shortName: 'R. Carlos', nickname: 'El Hombre Bala', countryId: 'bra', position: 'LI', otherPositions: ['CAI'], rating: 95, worldCupEdition: 2002 },
  { id: 'p-thiagosilva', name: 'Thiago Silva', shortName: 'T. Silva', nickname: 'O Monstro', countryId: 'bra', position: 'DFC', otherPositions: [], rating: 90, worldCupEdition: 2014 },
  { id: 'p-vini', name: 'Vinícius Jr.', shortName: 'Vini Jr.', nickname: 'Malvadeza', countryId: 'bra', position: 'EI', otherPositions: ['DC'], rating: 91, worldCupEdition: 2022 },
  { id: 'p-zico', name: 'Zico', shortName: 'Zico', nickname: 'O Galinho de Quintino', countryId: 'bra', position: 'MCO', otherPositions: ['SD', 'MC'], rating: 98, worldCupEdition: 1982 },
  { id: 'p-socrates', name: 'Sócrates', shortName: 'Sócrates', nickname: 'O Doutor', countryId: 'bra', position: 'MC', otherPositions: ['MCO'], rating: 96, worldCupEdition: 1982 },
  { id: 'p-djalmasantos', name: 'Djalma Santos', shortName: 'D. Santos', nickname: 'La Muralla', countryId: 'bra', position: 'LD', otherPositions: ['DFC'], rating: 96, worldCupEdition: 1958 },
  { id: 'p-niltonsantos', name: 'Nilton Santos', shortName: 'N. Santos', nickname: 'La Enciclopedia', countryId: 'bra', position: 'LI', otherPositions: ['DFC'], rating: 96, worldCupEdition: 1958 },
  { id: 'p-dida', name: 'Dida', shortName: 'Dida', nickname: 'La Muralla Silenciosa', countryId: 'bra', position: 'POR', otherPositions: [], rating: 93, worldCupEdition: 2006 },
  { id: 'p-neymar', name: 'Neymar Jr.', shortName: 'Neymar', nickname: 'O Menino', countryId: 'bra', position: 'EI', otherPositions: ['MCO', 'SD'], rating: 96, worldCupEdition: 2014 },
  { id: 'p-daniAlves', name: 'Dani Alves', shortName: 'Dani Alves', nickname: 'El Loco', countryId: 'bra', position: 'LD', otherPositions: ['CAD', 'MC'], rating: 93, worldCupEdition: 2014 },
  { id: 'p-lucio', name: 'Lúcio', shortName: 'Lúcio', nickname: 'O Cavalo', countryId: 'bra', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 2002 },
  { id: 'p-falcao', name: 'Paulo Roberto Falcão', shortName: 'Falcão', nickname: 'El octavo rey de Roma', countryId: 'bra', position: 'MC', otherPositions: ['MCD'], rating: 95, worldCupEdition: 1982 },
  { id: 'p-carlosalberto', name: 'Carlos Alberto Torres', shortName: 'C. Alberto', nickname: 'O Capitão do Tri', countryId: 'bra', position: 'LD', otherPositions: ['DFC'], rating: 97, worldCupEdition: 1970 },
  { id: 'p-clodoaldo', name: 'Clodoaldo Tavares', shortName: 'Clodoaldo', nickname: 'Coronel', countryId: 'bra', position: 'MCD', otherPositions: ['MC'], rating: 92, worldCupEdition: 1970 },
  { id: 'p-gerson', name: 'Gérson de Oliveira', shortName: 'Gérson', nickname: 'La Zurda de Oro', countryId: 'bra', position: 'MC', otherPositions: ['MCO'], rating: 94, worldCupEdition: 1970 },
  { id: 'p-taffarel', name: 'Cláudio Taffarel', shortName: 'Taffarel', nickname: 'San Taffarel', countryId: 'bra', position: 'POR', otherPositions: [], rating: 93, worldCupEdition: 1994 },

  // --- ARGENTINA (arg) ---
  { id: 'p-maradona', name: 'Diego Maradona', shortName: 'Maradona', nickname: 'El Pibe de Oro', countryId: 'arg', position: 'MCO', otherPositions: ['SD', 'DC'], rating: 99, worldCupEdition: 1986 },
  { id: 'p-messi', name: 'Lionel Messi', shortName: 'Messi', nickname: 'La Pulga', countryId: 'arg', position: 'ED', otherPositions: ['DC', 'MCO', 'SD'], rating: 98, worldCupEdition: 2022 },
  { id: 'p-kempes', name: 'Mario Kempes', shortName: 'Kempes', nickname: 'El Matador', countryId: 'arg', position: 'DC', otherPositions: ['EI', 'MCO'], rating: 95, worldCupEdition: 1978 },
  { id: 'p-passarella', name: 'Daniel Passarella', shortName: 'Passarella', nickname: 'El Gran Capitán', countryId: 'arg', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 1978 },
  { id: 'p-burruchaga', name: 'Jorge Burruchaga', shortName: 'Burruchaga', nickname: 'Burru', countryId: 'arg', position: 'MCO', otherPositions: ['MC', 'ED'], rating: 90, worldCupEdition: 1986 },
  { id: 'p-caniggia', name: 'Claudio Caniggia', shortName: 'Caniggia', nickname: 'El Pájaro', countryId: 'arg', position: 'ED', otherPositions: ['DC', 'EI'], rating: 91, worldCupEdition: 1990 },
  { id: 'p-batistuta', name: 'Gabriel Batistuta', shortName: 'Batistuta', nickname: 'Batigol', countryId: 'arg', position: 'DC', otherPositions: [], rating: 95, worldCupEdition: 1998 },
  { id: 'p-riquelme', name: 'Juan Román Riquelme', shortName: 'Riquelme', nickname: 'El Torero', countryId: 'arg', position: 'MCO', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-zanetti', name: 'Javier Zanetti', shortName: 'Zanetti', nickname: 'El Pupi', countryId: 'arg', position: 'LD', otherPositions: ['LI', 'MCD', 'MC'], rating: 93, worldCupEdition: 2002 },
  { id: 'p-mascherano', name: 'Javier Mascherano', shortName: 'Mascherano', nickname: 'El Jefecito', countryId: 'arg', position: 'MCD', otherPositions: ['DFC'], rating: 91, worldCupEdition: 2014 },
  { id: 'p-dimaria', name: 'Ángel Di María', shortName: 'Di María', nickname: 'El Fideo', countryId: 'arg', position: 'ED', otherPositions: ['EI', 'MCO', 'MC'], rating: 91, worldCupEdition: 2022 },
  { id: 'p-martinez', name: 'Emiliano Martínez', shortName: 'Dibu Martínez', nickname: 'El Dibu', countryId: 'arg', position: 'POR', otherPositions: [], rating: 89, worldCupEdition: 2022 },
  { id: 'p-alvarez', name: 'Julián Álvarez', shortName: 'J. Álvarez', nickname: 'La Araña', countryId: 'arg', position: 'DC', otherPositions: ['ED', 'EI'], rating: 87, worldCupEdition: 2022 },
  { id: 'p-lautaro', name: 'Lautaro Martínez', shortName: 'Lautaro', nickname: 'El Toro', countryId: 'arg', position: 'DC', otherPositions: [], rating: 89, worldCupEdition: 2022 },
  { id: 'p-romero', name: 'Cuti Romero', shortName: 'Cuti Romero', nickname: 'Cuti', countryId: 'arg', position: 'DFC', otherPositions: [], rating: 88, worldCupEdition: 2022 },
  { id: 'p-redondo', name: 'Fernando Redondo', shortName: 'Redondo', nickname: 'El Príncipe', countryId: 'arg', position: 'MCD', otherPositions: ['MC'], rating: 95, worldCupEdition: 1994 },
  { id: 'p-ortega', name: 'Ariel Ortega', shortName: 'Ortega', nickname: 'El Burrito', countryId: 'arg', position: 'MCO', otherPositions: ['ED', 'SD'], rating: 92, worldCupEdition: 1998 },
  { id: 'p-fillol', name: 'Ubaldo Fillol', shortName: 'Fillol', nickname: 'El Pato', countryId: 'arg', position: 'POR', otherPositions: [], rating: 95, worldCupEdition: 1978 },
  { id: 'p-aimar', name: 'Pablo Aimar', shortName: 'Aimar', nickname: 'El Payaso', countryId: 'arg', position: 'MCO', otherPositions: ['MC'], rating: 93, worldCupEdition: 2002 },
  { id: 'p-simeone', name: 'Diego Simeone', shortName: 'Simeone', nickname: 'El Cholo', countryId: 'arg', position: 'MCD', otherPositions: ['MC'], rating: 92, worldCupEdition: 1994 },
  { id: 'p-tevez', name: 'Carlos Tévez', shortName: 'Tévez', nickname: 'El Apache', countryId: 'arg', position: 'DC', otherPositions: ['SD', 'MCO'], rating: 93, worldCupEdition: 2010 },
  { id: 'p-veron', name: 'Juan Sebastián Verón', shortName: 'Verón', nickname: 'La Brujita', countryId: 'arg', position: 'MC', otherPositions: ['MCO'], rating: 93, worldCupEdition: 1998 },
  { id: 'p-crespo', name: 'Hernán Crespo', shortName: 'Crespo', nickname: 'Valdanito', countryId: 'arg', position: 'DC', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-sorin', name: 'Juan Pablo Sorín', shortName: 'Sorín', nickname: 'Juampi', countryId: 'arg', position: 'LI', otherPositions: ['CAI', 'MC'], rating: 90, worldCupEdition: 2006 },
  { id: 'p-ayala', name: 'Roberto Ayala', shortName: 'Ayala', nickname: 'El Ratón', countryId: 'arg', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-valdanog', name: 'Jorge Valdano', shortName: 'Valdano', nickname: 'El Filósofo', countryId: 'arg', position: 'DC', otherPositions: ['EI'], rating: 92, worldCupEdition: 1986 },
  { id: 'p-ruggeri', name: 'Oscar Ruggeri', shortName: 'Ruggeri', nickname: 'El Cabezón', countryId: 'arg', position: 'DFC', otherPositions: [], rating: 93, worldCupEdition: 1986 },
  { id: 'p-goycochea', name: 'Sergio Goycochea', shortName: 'Goycochea', nickname: 'El Vasco', countryId: 'arg', position: 'POR', otherPositions: [], rating: 91, worldCupEdition: 1990 },

  // --- ALEMANIA (deu) ---
  { id: 'p-beckenbauer', name: 'Franz Beckenbauer', shortName: 'Beckenbauer', nickname: 'Der Kaiser', countryId: 'deu', position: 'DFC', otherPositions: ['MCD', 'MC'], rating: 98, worldCupEdition: 1974 },
  { id: 'p-gerdmuller', name: 'Gerd Müller', shortName: 'G. Müller', nickname: 'Der Bomber', countryId: 'deu', position: 'DC', otherPositions: [], rating: 97, worldCupEdition: 1974 },
  { id: 'p-seppmaier', name: 'Sepp Maier', shortName: 'Maier', nickname: 'Die Katze von Anzing', countryId: 'deu', position: 'POR', otherPositions: [], rating: 94, worldCupEdition: 1974 },
  { id: 'p-rummenigge', name: 'Karl-Heinz Rummenigge', shortName: 'Rummenigge', nickname: 'Kalle', countryId: 'deu', position: 'DC', otherPositions: ['ED', 'SD'], rating: 95, worldCupEdition: 1982 },
  { id: 'p-matthaus', name: 'Lothar Matthäus', shortName: 'Matthäus', nickname: 'Der Leitwolf', countryId: 'deu', position: 'MC', otherPositions: ['DFC', 'MCD', 'MCO'], rating: 97, worldCupEdition: 1990 },
  { id: 'p-klinsmann', name: 'Jürgen Klinsmann', shortName: 'Klinsmann', nickname: 'El Tiburón Dorado', countryId: 'deu', position: 'DC', otherPositions: [], rating: 93, worldCupEdition: 1990 },
  { id: 'p-brehme', name: 'Andreas Brehme', shortName: 'Brehme', nickname: 'El Ambidiestro', countryId: 'deu', position: 'LI', otherPositions: ['LD', 'MCD'], rating: 92, worldCupEdition: 1990 },
  { id: 'p-kahn', name: 'Oliver Kahn', shortName: 'Kahn', nickname: 'Der Titan', countryId: 'deu', position: 'POR', otherPositions: [], rating: 95, worldCupEdition: 2002 },
  { id: 'p-klose', name: 'Miroslav Klose', shortName: 'Klose', nickname: 'Salto-Klose', countryId: 'deu', position: 'DC', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-lahm', name: 'Philipp Lahm', shortName: 'Lahm', nickname: 'El Botón Mágico', countryId: 'deu', position: 'LD', otherPositions: ['LI', 'MCD'], rating: 94, worldCupEdition: 2014 },
  { id: 'p-schweinsteiger', name: 'Bastian Schweinsteiger', shortName: 'Schweinsteiger', nickname: 'Schweini', countryId: 'deu', position: 'MC', otherPositions: ['MCD', 'EI', 'ED'], rating: 92, worldCupEdition: 2014 },
  { id: 'p-neuer', name: 'Manuel Neuer', shortName: 'Neuer', nickname: 'The Rekordmeister Wall', countryId: 'deu', position: 'POR', otherPositions: [], rating: 92, worldCupEdition: 2014 },
  { id: 'p-kroos', name: 'Toni Kroos', shortName: 'Kroos', nickname: 'El Metrónomo', countryId: 'deu', position: 'MC', otherPositions: ['MCO', 'MCD'], rating: 93, worldCupEdition: 2014 },
  { id: 'p-thomasmuller', name: 'Thomas Müller', shortName: 'T. Müller', nickname: 'Der Raumdeuter', countryId: 'deu', position: 'DC', otherPositions: ['MCO', 'ED', 'SD'], rating: 90, worldCupEdition: 2010 },
  { id: 'p-musiala', name: 'Jamal Musiala', shortName: 'Musiala', nickname: 'Bambi', countryId: 'deu', position: 'MCO', otherPositions: ['EI', 'ED', 'MC'], rating: 88, worldCupEdition: 2022 },
  { id: 'p-netzer', name: 'Günter Netzer', shortName: 'Netzer', nickname: 'Karajan del fútbol', countryId: 'deu', position: 'MC', otherPositions: ['MCO'], rating: 95, worldCupEdition: 1974 },
  { id: 'p-sammer', name: 'Matthias Sammer', shortName: 'Sammer', nickname: 'El Barón Rojo', countryId: 'deu', position: 'DFC', otherPositions: ['MCD'], rating: 95, worldCupEdition: 1994 },
  { id: 'p-breitner', name: 'Paul Breitner', shortName: 'Breitner', nickname: 'Der Afro-Kaiser', countryId: 'deu', position: 'MC', otherPositions: ['LI'], rating: 96, worldCupEdition: 1974 },
  { id: 'p-ballack', name: 'Michael Ballack', shortName: 'Ballack', nickname: 'El Pequeño Kaiser', countryId: 'deu', position: 'MC', otherPositions: ['MCO', 'MCD'], rating: 94, worldCupEdition: 2002 },
  { id: 'p-ozil', name: 'Mesut Özil', shortName: 'Özil', nickname: 'El Mago de Öz', countryId: 'deu', position: 'MCO', otherPositions: ['EI', 'ED'], rating: 92, worldCupEdition: 2010 },
  { id: 'p-hummels', name: 'Mats Hummels', shortName: 'Hummels', nickname: 'El Muro', countryId: 'deu', position: 'DFC', otherPositions: [], rating: 89, worldCupEdition: 2014 },
  { id: 'p-podolski', name: 'Lukas Podolski', shortName: 'Podolski', nickname: 'Príncipe Poldi', countryId: 'deu', position: 'EI', otherPositions: ['DC'], rating: 89, worldCupEdition: 2006 },
  { id: 'p-reus', name: 'Marco Reus', shortName: 'Reus', nickname: 'Rolls Reus', countryId: 'deu', position: 'MCO', otherPositions: ['EI', 'ED', 'SD'], rating: 91, worldCupEdition: 2018 },
  { id: 'p-voller', name: 'Rudi Völler', shortName: 'Völler', nickname: 'Tante Käthe', countryId: 'deu', position: 'DC', otherPositions: [], rating: 94, worldCupEdition: 1990 },
  { id: 'p-effenberg', name: 'Stefan Effenberg', shortName: 'Effenberg', nickname: 'El Tigre', countryId: 'deu', position: 'MC', otherPositions: ['MCD'], rating: 92, worldCupEdition: 1994 },
  { id: 'p-walter', name: 'Fritz Walter', shortName: 'Walter', nickname: 'El Héroe de Berna', countryId: 'deu', position: 'MCO', otherPositions: ['DC'], rating: 96, worldCupEdition: 1954 },
  { id: 'p-schon', name: 'Helmut Rahn', shortName: 'Rahn', nickname: 'Der Boss', countryId: 'deu', position: 'ED', otherPositions: ['DC'], rating: 95, worldCupEdition: 1954 },
  { id: 'p-rudiger', name: 'Antonio Rüdiger', shortName: 'Rüdiger', nickname: 'El Loco', countryId: 'deu', position: 'DFC', otherPositions: ['LD'], rating: 88, worldCupEdition: 2022 },

  // --- ITALIA (ita) ---
  { id: 'p-zoff', name: 'Dino Zoff', shortName: 'Zoff', nickname: 'El Mito', countryId: 'ita', position: 'POR', otherPositions: [], rating: 95, worldCupEdition: 1982 },
  { id: 'p-paolorossi', name: 'Paolo Rossi', shortName: 'P. Rossi', nickname: 'Pablito', countryId: 'ita', position: 'DC', otherPositions: ['ED'], rating: 95, worldCupEdition: 1982 },
  { id: 'p-baresi', name: 'Franco Baresi', shortName: 'Baresi', nickname: 'Piscinin', countryId: 'ita', position: 'DFC', otherPositions: ['MCD'], rating: 97, worldCupEdition: 1990 },
  { id: 'p-bergomi', name: 'Giuseppe Bergomi', shortName: 'Bergomi', nickname: 'Lo Zio', countryId: 'ita', position: 'DFC', otherPositions: ['LD', 'LI'], rating: 92, worldCupEdition: 1982 },
  { id: 'p-baggio', name: 'Roberto Baggio', shortName: 'Baggio', nickname: 'Il Divin Codino', countryId: 'ita', position: 'MCO', otherPositions: ['SD', 'DC'], rating: 96, worldCupEdition: 1994 },
  { id: 'p-maldini', name: 'Paolo Maldini', shortName: 'Maldini', nickname: 'Cuore di Drago', countryId: 'ita', position: 'LI', otherPositions: ['DFC'], rating: 98, worldCupEdition: 1994 },
  { id: 'p-delpiero', name: 'Alessandro Del Piero', shortName: 'Del Piero', nickname: 'Pinturicchio', countryId: 'ita', position: 'DC', otherPositions: ['SD', 'MCO', 'EI'], rating: 95, worldCupEdition: 2006 },
  { id: 'p-totti', name: 'Francesco Totti', shortName: 'Totti', nickname: 'Il Bimbo de Oro', countryId: 'ita', position: 'MCO', otherPositions: ['SD', 'DC'], rating: 95, worldCupEdition: 2006 },
  { id: 'p-cannavaro', name: 'Fabio Cannavaro', shortName: 'Cannavaro', nickname: 'Il Muro di Berlino', countryId: 'ita', position: 'DFC', otherPositions: ['LD'], rating: 97, worldCupEdition: 2006 },
  { id: 'p-buffon', name: 'Gianluigi Buffon', shortName: 'Buffon', nickname: 'Gigi', countryId: 'ita', position: 'POR', otherPositions: [], rating: 96, worldCupEdition: 2006 },
  { id: 'p-pirlo', name: 'Andrea Pirlo', shortName: 'Pirlo', nickname: 'Il Maestro', countryId: 'ita', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 96, worldCupEdition: 2006 },
  { id: 'p-derossi', name: 'Daniele De Rossi', shortName: 'De Rossi', nickname: 'Capitan Futuro', countryId: 'ita', position: 'MCD', otherPositions: ['MC', 'DFC'], rating: 90, worldCupEdition: 2006 },
  { id: 'p-chiellini', name: 'Giorgio Chiellini', shortName: 'Chiellini', nickname: 'King Kong', countryId: 'ita', position: 'DFC', otherPositions: ['LI'], rating: 91, worldCupEdition: 2014 },
  { id: 'p-bonucci', name: 'Leonardo Bonucci', shortName: 'Bonucci', nickname: 'The Architect Centerback', countryId: 'ita', position: 'DFC', otherPositions: [], rating: 89, worldCupEdition: 2014 },
  { id: 'p-verratti', name: 'Marco Verratti', shortName: 'Verratti', nickname: 'Il Gufetto', countryId: 'ita', position: 'MC', otherPositions: ['MCD'], rating: 88, worldCupEdition: 2014 },
  { id: 'p-nesta', name: 'Alessandro Nesta', shortName: 'Nesta', nickname: 'La Tempesta Perfetta', countryId: 'ita', position: 'DFC', otherPositions: [], rating: 97, worldCupEdition: 2006 },
  { id: 'p-scirea', name: 'Gaetano Scirea', shortName: 'Scirea', nickname: 'El Caballero del Área', countryId: 'ita', position: 'DFC', otherPositions: ['MCD'], rating: 97, worldCupEdition: 1982 },
  { id: 'p-gentile', name: 'Claudio Gentile', shortName: 'Gentile', nickname: 'Gaddafi', countryId: 'ita', position: 'DFC', otherPositions: ['LD'], rating: 94, worldCupEdition: 1982 },
  { id: 'p-zambrotta', name: 'Gianluca Zambrotta', shortName: 'Zambrotta', nickname: 'El Camaleón', countryId: 'ita', position: 'LD', otherPositions: ['LI', 'CAD', 'CAI'], rating: 93, worldCupEdition: 2006 },
  { id: 'p-vieri', name: 'Christian Vieri', shortName: 'Vieri', nickname: 'Bobo', countryId: 'ita', position: 'DC', otherPositions: [], rating: 94, worldCupEdition: 1998 },
  { id: 'p-inzaghi', name: 'Filippo Inzaghi', shortName: 'Inzaghi', nickname: 'Superpippo', countryId: 'ita', position: 'DC', otherPositions: [], rating: 93, worldCupEdition: 2006 },
  { id: 'p-gattuso', name: 'Gennaro Gattuso', shortName: 'Gattuso', nickname: 'Ringhio', countryId: 'ita', position: 'MCD', otherPositions: ['MC'], rating: 92, worldCupEdition: 2006 },
  { id: 'p-delvecchio', name: 'Marco Delvecchio', shortName: 'Delvecchio', nickname: 'SuperMarco', countryId: 'ita', position: 'DC', otherPositions: ['ED', 'EI'], rating: 88, worldCupEdition: 2002 },
  { id: 'p-donnarumma', name: 'Gianluigi Donnarumma', shortName: 'Donnarumma', nickname: 'Gigio', countryId: 'ita', position: 'POR', otherPositions: [], rating: 89, worldCupEdition: 2022 },
  { id: 'p-mancini', name: 'Roberto Mancini', shortName: 'Mancini', nickname: 'Il Bimbo', countryId: 'ita', position: 'MCO', otherPositions: ['SD'], rating: 93, worldCupEdition: 1990 },
  { id: 'p-meazza', name: 'Giuseppe Meazza', shortName: 'Meazza', nickname: 'Il Balilla', countryId: 'ita', position: 'DC', otherPositions: ['MCO', 'SD'], rating: 98, worldCupEdition: 1938 },
  { id: 'p-altobelli', name: 'Alessandro Altobelli', shortName: 'Altobelli', nickname: 'Spillo', countryId: 'ita', position: 'DC', otherPositions: [], rating: 92, worldCupEdition: 1982 },
  { id: 'p-materazzi', name: 'Marco Materazzi', shortName: 'Materazzi', nickname: 'Matrix', countryId: 'ita', position: 'DFC', otherPositions: [], rating: 91, worldCupEdition: 2006 },

  // --- FRANCIA (fra) ---
  { id: 'p-mbappe', name: 'Kylian Mbappé', shortName: 'Mbappé', nickname: 'Donatello', countryId: 'fra', position: 'DC', otherPositions: ['EI', 'ED'], rating: 92, worldCupEdition: 2022 },
  { id: 'p-zidane', name: 'Zinedine Zidane', shortName: 'Zidane', nickname: 'Zizou', countryId: 'fra', position: 'MCO', otherPositions: ['MC'], rating: 95, worldCupEdition: 1998 },
  { id: 'p-griezmann', name: 'Antoine Griezmann', shortName: 'Griezmann', nickname: 'El Principito', countryId: 'fra', position: 'MCO', otherPositions: ['DC', 'SD', 'MC'], rating: 87, worldCupEdition: 2018 },
  { id: 'p-saliba', name: 'William Saliba', shortName: 'Saliba', nickname: 'El Muro de Bondy', countryId: 'fra', position: 'DFC', otherPositions: [], rating: 88, worldCupEdition: 2022 },
  { id: 'p-maignan', name: 'Mike Maignan', shortName: 'Maignan', nickname: 'Magic Mike', countryId: 'fra', position: 'POR', otherPositions: [], rating: 86, worldCupEdition: 2022 },
  { id: 'p-platini', name: 'Michel Platini', shortName: 'Platini', nickname: 'Le Roi', countryId: 'fra', position: 'MCO', otherPositions: ['MC', 'SD'], rating: 98, worldCupEdition: 1986 },
  { id: 'p-henry', name: 'Thierry Henry', shortName: 'Henry', nickname: 'Tití', countryId: 'fra', position: 'DC', otherPositions: ['EI', 'ED'], rating: 97, worldCupEdition: 2006 },
  { id: 'p-vieira', name: 'Patrick Vieira', shortName: 'Vieira', nickname: 'El Pulpo', countryId: 'fra', position: 'MCD', otherPositions: ['MC'], rating: 95, worldCupEdition: 1998 },
  { id: 'p-desailly', name: 'Marcel Desailly', shortName: 'Desailly', nickname: 'La Roca', countryId: 'fra', position: 'DFC', otherPositions: ['MCD'], rating: 95, worldCupEdition: 1998 },
  { id: 'p-thuram', name: 'Lilian Thuram', shortName: 'Thuram', nickname: 'El Filósofo de Guadalupe', countryId: 'fra', position: 'DFC', otherPositions: ['LD'], rating: 94, worldCupEdition: 1998 },
  { id: 'p-cantona', name: 'Eric Cantona', shortName: 'Cantona', nickname: 'The King', countryId: 'fra', position: 'DC', otherPositions: ['MCO', 'SD'], rating: 95, worldCupEdition: 1994 },
  { id: 'p-ribery', name: 'Franck Ribéry', shortName: 'Ribéry', nickname: 'Scarface', countryId: 'fra', position: 'EI', otherPositions: ['ED', 'MCO'], rating: 93, worldCupEdition: 2006 },
  { id: 'p-pogba', name: 'Paul Pogba', shortName: 'Pogba', nickname: 'La Pioche', countryId: 'fra', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 89, worldCupEdition: 2018 },
  { id: 'p-ginola', name: 'David Ginola', shortName: 'Ginola', nickname: 'El Magnífico', countryId: 'fra', position: 'EI', otherPositions: ['MCO', 'SD'], rating: 91, worldCupEdition: 1994 },
  { id: 'p-blanc', name: 'Laurent Blanc', shortName: 'Blanc', nickname: 'Le Président', countryId: 'fra', position: 'DFC', otherPositions: ['MCD'], rating: 94, worldCupEdition: 1998 },
  { id: 'p-makelele', name: 'Claude Makélélé', shortName: 'Makélélé', nickname: 'El Reloj Humano', countryId: 'fra', position: 'MCD', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-benzema', name: 'Karim Benzema', shortName: 'Benzema', nickname: 'El Gato', countryId: 'fra', position: 'DC', otherPositions: [], rating: 93, worldCupEdition: 2014 },
  { id: 'p-fontaine', name: 'Just Fontaine', shortName: 'Fontaine', nickname: 'Justo', countryId: 'fra', position: 'DC', otherPositions: [], rating: 97, worldCupEdition: 1958 },
  { id: 'p-kante', name: 'N\'Golo Kanté', shortName: 'Kanté', nickname: 'El Motorcito', countryId: 'fra', position: 'MCD', otherPositions: ['MC'], rating: 93, worldCupEdition: 2018 },
  { id: 'p-lloris', name: 'Hugo Lloris', shortName: 'Lloris', nickname: 'San Hugo', countryId: 'fra', position: 'POR', otherPositions: [], rating: 90, worldCupEdition: 2018 },

  // --- INGLATERRA (eng) ---
  { id: 'p-kane', name: 'Harry Kane', shortName: 'Kane', nickname: 'The HurriKane', countryId: 'eng', position: 'DC', otherPositions: [], rating: 90, worldCupEdition: 2018 },
  { id: 'p-bellingham', name: 'Jude Bellingham', shortName: 'Bellingham', nickname: 'Hey Jude', countryId: 'eng', position: 'MC', otherPositions: ['MCO', 'MCD'], rating: 90, worldCupEdition: 2022 },
  { id: 'p-saka', name: 'Bukayo Saka', shortName: 'Saka', nickname: 'Starboy', countryId: 'eng', position: 'ED', otherPositions: ['EI', 'LD', 'CAD'], rating: 87, worldCupEdition: 2022 },
  { id: 'p-stones', name: 'John Stones', shortName: 'Stones', nickname: 'The Barnsley Baresi', countryId: 'eng', position: 'DFC', otherPositions: ['MCD', 'LD'], rating: 85, worldCupEdition: 2018 },
  { id: 'p-charlton', name: 'Bobby Charlton', shortName: 'Charlton', nickname: 'Sir Bobby', countryId: 'eng', position: 'MCO', otherPositions: ['MC', 'DC'], rating: 98, worldCupEdition: 1966 },
  { id: 'p-lineker', name: 'Gary Lineker', shortName: 'Lineker', nickname: 'El Ejecutor Impoluto', countryId: 'eng', position: 'DC', otherPositions: [], rating: 95, worldCupEdition: 1986 },
  { id: 'p-gascoigne', name: 'Paul Gascoigne', shortName: 'Gazza', nickname: 'Gazza', countryId: 'eng', position: 'MC', otherPositions: ['MCO'], rating: 94, worldCupEdition: 1990 },
  { id: 'p-gerrard', name: 'Steven Gerrard', shortName: 'Gerrard', nickname: 'Stevie G', countryId: 'eng', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 95, worldCupEdition: 2006 },
  { id: 'p-lampard', name: 'Frank Lampard', shortName: 'Lampard', nickname: 'Super Frankie', countryId: 'eng', position: 'MC', otherPositions: ['MCO'], rating: 95, worldCupEdition: 2006 },
  { id: 'p-rooney', name: 'Wayne Rooney', shortName: 'Rooney', nickname: 'The Wonder Boy', countryId: 'eng', position: 'DC', otherPositions: ['SD', 'MCO', 'MC'], rating: 96, worldCupEdition: 2006 },
  { id: 'p-terry', name: 'John Terry', shortName: 'Terry', nickname: 'Mr. Chelsea', countryId: 'eng', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-rio', name: 'Rio Ferdinand', shortName: 'Ferdinand', nickname: 'Slick Rio', countryId: 'eng', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 2002 },
  { id: 'p-cole', name: 'Ashley Cole', shortName: 'A. Cole', nickname: 'Cashley', countryId: 'eng', position: 'LI', otherPositions: ['CAI'], rating: 93, worldCupEdition: 2006 },
  { id: 'p-shearer', name: 'Alan Shearer', shortName: 'Shearer', nickname: 'The Smokey Striker', countryId: 'eng', position: 'DC', otherPositions: [], rating: 95, worldCupEdition: 1998 },
  { id: 'p-beckham', name: 'David Beckham', shortName: 'Beckham', nickname: 'Spice Boy', countryId: 'eng', position: 'ED', otherPositions: ['MC'], rating: 96, worldCupEdition: 2002 },
  { id: 'p-scholes', name: 'Paul Scholes', shortName: 'Scholes', nickname: 'The Ginger Prince', countryId: 'eng', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 94, worldCupEdition: 1998 },
  { id: 'p-moore', name: 'Bobby Moore', shortName: 'Moore', nickname: 'The Golden Captain', countryId: 'eng', position: 'DFC', otherPositions: [], rating: 97, worldCupEdition: 1966 },
  { id: 'p-banks', name: 'Gordon Banks', shortName: 'Banks', nickname: 'El Chino', countryId: 'eng', position: 'POR', otherPositions: [], rating: 96, worldCupEdition: 1966 },
  { id: 'p-owen', name: 'Michael Owen', shortName: 'Owen', nickname: 'The Golden Boy', countryId: 'eng', position: 'DC', otherPositions: [], rating: 93, worldCupEdition: 1998 },

  // --- PORTUGAL (prt) ---
  { id: 'p-cr7', name: 'Cristiano Ronaldo', shortName: 'Cristiano', nickname: 'CR7 / El Bicho', countryId: 'prt', position: 'DC', otherPositions: ['EI', 'ED'], rating: 91, worldCupEdition: 2006 },
  { id: 'p-leao', name: 'Rafael Leão', shortName: 'Leão', nickname: 'El Surfista del Gol', countryId: 'prt', position: 'EI', otherPositions: ['DC'], rating: 86, worldCupEdition: 2022 },
  { id: 'p-bruno', name: 'Bruno Fernandes', shortName: 'B. Fernandes', nickname: 'El Arquitecto de Maia', countryId: 'prt', position: 'MCO', otherPositions: ['MC'], rating: 88, worldCupEdition: 2022 },
  { id: 'p-dias', name: 'Rúben Dias', shortName: 'Rúben Dias', nickname: 'El Jefe', countryId: 'prt', position: 'DFC', otherPositions: [], rating: 89, worldCupEdition: 2022 },
  { id: 'p-costa', name: 'Diogo Costa', shortName: 'D. Costa', nickname: 'El Parapenaltis', countryId: 'prt', position: 'POR', otherPositions: [], rating: 85, worldCupEdition: 2022 },
  { id: 'p-eusebio', name: 'Eusébio da Silva', shortName: 'Eusébio', nickname: 'O Pantera Negra', countryId: 'prt', position: 'DC', otherPositions: ['SD'], rating: 98, worldCupEdition: 1966 },
  { id: 'p-figo', name: 'Luís Figo', shortName: 'Figo', nickname: 'O Conquistador', countryId: 'prt', position: 'ED', otherPositions: ['EI', 'MCO'], rating: 96, worldCupEdition: 2006 },
  { id: 'p-ruicosta', name: 'Rui Costa', shortName: 'Rui Costa', nickname: 'O Maestro', countryId: 'prt', position: 'MCO', otherPositions: ['MC'], rating: 94, worldCupEdition: 2002 },
  { id: 'p-deco', name: 'Deco', shortName: 'Deco', nickname: 'O Mágico', countryId: 'prt', position: 'MC', otherPositions: ['MCO'], rating: 93, worldCupEdition: 2006 },
  { id: 'p-pepe', name: 'Képler Laveran (Pepe)', shortName: 'Pepe', nickname: 'El Muro de Funchal', countryId: 'prt', position: 'DFC', otherPositions: [], rating: 93, worldCupEdition: 2014 },
  { id: 'p-nani', name: 'Luís Carlos (Nani)', shortName: 'Nani', nickname: 'El Volador', countryId: 'prt', position: 'ED', otherPositions: ['EI'], rating: 90, worldCupEdition: 2014 },
  { id: 'p-ricardocarvalho', name: 'Ricardo Carvalho', shortName: 'R. Carvalho', nickname: 'El Inteligente', countryId: 'prt', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 2006 },
  { id: 'p-joaomoutinho', name: 'João Moutinho', shortName: 'Moutinho', nickname: 'El Compás', countryId: 'prt', position: 'MC', otherPositions: ['MCD'], rating: 89, worldCupEdition: 2014 },
  { id: 'p-bernardosilva', name: 'Bernardo Silva', shortName: 'Bernardo', nickname: 'Bubblegum', countryId: 'prt', position: 'MCO', otherPositions: ['ED', 'MC'], rating: 90, worldCupEdition: 2018 },
  { id: 'p-vitinha', name: 'Vítor Machado (Vitinha)', shortName: 'Vitinha', nickname: 'El Motorcito de Ouro', countryId: 'prt', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 87, worldCupEdition: 2022 },
  { id: 'p-coluna', name: 'Mário Coluna', shortName: 'Coluna', nickname: 'O Monstro Sagrado', countryId: 'prt', position: 'MC', otherPositions: ['MCD'], rating: 94, worldCupEdition: 1966 },
  { id: 'p-futre', name: 'Paulo Futre', shortName: 'Futre', nickname: 'El Hijo del Viento', countryId: 'prt', position: 'EI', otherPositions: ['ED', 'SD'], rating: 92, worldCupEdition: 1986 },
  { id: 'p-pauleta', name: 'Pedro Pauleta', shortName: 'Pauleta', nickname: 'O Ciclone dos Açores', countryId: 'prt', position: 'DC', otherPositions: [], rating: 91, worldCupEdition: 2002 },

  // --- URUGUAY (uru) ---
  { id: 'p-obdulio', name: 'Obdulio Varela', shortName: 'Varela', nickname: 'El Negro Jefe', countryId: 'uru', position: 'MCD', otherPositions: ['MC', 'DFC'], rating: 96, worldCupEdition: 1950 },
  { id: 'p-ghiggia', name: 'Alcides Ghiggia', shortName: 'Ghiggia', nickname: 'El Verdugo del Maracaná', countryId: 'uru', position: 'ED', otherPositions: ['DC'], rating: 94, worldCupEdition: 1950 },
  { id: 'p-francescoli', name: 'Enzo Francescoli', shortName: 'Francescoli', nickname: 'El Príncipe', countryId: 'uru', position: 'MCO', otherPositions: ['SD', 'DC'], rating: 95, worldCupEdition: 1986 },
  { id: 'p-forlan', name: 'Diego Forlán', shortName: 'Forlán', nickname: 'Cachavacha', countryId: 'uru', position: 'DC', otherPositions: ['SD', 'MCO'], rating: 95, worldCupEdition: 2010 },
  { id: 'p-suarez', name: 'Luis Suárez', shortName: 'Suárez', nickname: 'El Pistolero', countryId: 'uru', position: 'DC', otherPositions: [], rating: 94, worldCupEdition: 2010 },
  { id: 'p-cavani', name: 'Edinson Cavani', shortName: 'Cavani', nickname: 'El Matador', countryId: 'uru', position: 'DC', otherPositions: ['EI', 'ED'], rating: 92, worldCupEdition: 2018 },
  { id: 'p-valverde', name: 'Federico Valverde', shortName: 'Valverde', nickname: 'El Halcón', countryId: 'uru', position: 'MC', otherPositions: ['MCD', 'ED', 'LD'], rating: 90, worldCupEdition: 2022 },
  { id: 'p-godin', name: 'Diego Godín', shortName: 'Godín', nickname: 'El Faraón', countryId: 'uru', position: 'DFC', otherPositions: [], rating: 92, worldCupEdition: 2014 },
  { id: 'p-araujo', name: 'Ronald Araújo', shortName: 'Araújo', nickname: 'La Muralla Rivera', countryId: 'uru', position: 'DFC', otherPositions: ['LD'], rating: 88, worldCupEdition: 2022 },
  { id: 'p-rochet', name: 'Sergio Rochet', shortName: 'Rochet', nickname: 'El Chino', countryId: 'uru', position: 'POR', otherPositions: [], rating: 83, worldCupEdition: 2022 },
  { id: 'p-schiaffino', name: 'Juan Alberto Schiaffino', shortName: 'Schiaffino', nickname: 'Pepe', countryId: 'uru', position: 'MCO', otherPositions: ['DC', 'SD'], rating: 97, worldCupEdition: 1950 },
  { id: 'p-nasazzi', name: 'José Nasazzi', shortName: 'Nasazzi', nickname: 'El Mariscal', countryId: 'uru', position: 'DFC', otherPositions: ['LD'], rating: 96, worldCupEdition: 1930 },
  { id: 'p-lugano', name: 'Diego Lugano', shortName: 'Lugano', nickname: 'La Tota', countryId: 'uru', position: 'DFC', otherPositions: [], rating: 90, worldCupEdition: 2010 },

  // --- PAÍSES BAJOS (nld) ---
  { id: 'p-cruyff', name: 'Johan Cruyff', shortName: 'Cruyff', nickname: 'El Flaco / El Salvador', countryId: 'nld', position: 'DC', otherPositions: ['MCO', 'SD', 'EI'], rating: 99, worldCupEdition: 1974 },
  { id: 'p-neeskens', name: 'Johan Neeskens', shortName: 'Neeskens', nickname: 'Johan Segundo', countryId: 'nld', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 95, worldCupEdition: 1974 },
  { id: 'p-vanbasten', name: 'Marco van Basten', shortName: 'Van Basten', nickname: 'El Cisne de Utrecht', countryId: 'nld', position: 'DC', otherPositions: [], rating: 98, worldCupEdition: 1990 },
  { id: 'p-gullit', name: 'Ruud Gullit', shortName: 'Gullit', nickname: 'El Tulipán Negro', countryId: 'nld', position: 'MC', otherPositions: ['MCO', 'DFC', 'DC', 'LD'], rating: 97, worldCupEdition: 1990 },
  { id: 'p-rijkaard', name: 'Frank Rijkaard', shortName: 'Rijkaard', nickname: 'El Cometa', countryId: 'nld', position: 'MCD', otherPositions: ['DFC', 'MC'], rating: 96, worldCupEdition: 1990 },
  { id: 'p-koeman', name: 'Ronald Koeman', shortName: 'Koeman', nickname: 'Tintín', countryId: 'nld', position: 'DFC', otherPositions: ['MCD'], rating: 95, worldCupEdition: 1994 },
  { id: 'p-bergkamp', name: 'Dennis Bergkamp', shortName: 'Bergkamp', nickname: 'The Non-Flying Dutchman', countryId: 'nld', position: 'MCO', otherPositions: ['SD', 'DC'], rating: 96, worldCupEdition: 1998 },
  { id: 'p-robben', name: 'Arjen Robben', shortName: 'Robben', nickname: 'El Expreso de Bedum', countryId: 'nld', position: 'ED', otherPositions: ['EI', 'SD', 'DC'], rating: 95, worldCupEdition: 2014 },
  { id: 'p-sneijder', name: 'Wesley Sneijder', shortName: 'Sneijder', nickname: 'El Francotirador', countryId: 'nld', position: 'MCO', otherPositions: ['MC'], rating: 94, worldCupEdition: 2010 },
  { id: 'p-vandersar', name: 'Edwin van der Sar', shortName: 'Van der Sar', nickname: 'El Pino', countryId: 'nld', position: 'POR', otherPositions: [], rating: 95, worldCupEdition: 1998 },
  { id: 'p-vandijk', name: 'Virgil van Dijk', shortName: 'Van Dijk', nickname: 'The Big Virg', countryId: 'nld', position: 'DFC', otherPositions: [], rating: 90, worldCupEdition: 2022 },
  { id: 'p-dejong', name: 'Frenkie de Jong', shortName: 'De Jong', nickname: 'El Ilusionista', countryId: 'nld', position: 'MC', otherPositions: ['MCD', 'DFC'], rating: 88, worldCupEdition: 2022 },
  { id: 'p-gakpo', name: 'Cody Gakpo', shortName: 'Gakpo', nickname: 'Eindhoven Eagle', countryId: 'nld', position: 'EI', otherPositions: ['DC', 'MCO'], rating: 86, worldCupEdition: 2022 },
  { id: 'p-depay', name: 'Memphis Depay', shortName: 'Memphis', nickname: 'Dream Chaser', countryId: 'nld', position: 'DC', otherPositions: ['EI', 'SD'], rating: 85, worldCupEdition: 2022 },
  { id: 'p-dumfries', name: 'Denzel Dumfries', shortName: 'Dumfries', nickname: 'El Búfalo', countryId: 'nld', position: 'LD', otherPositions: ['CAD'], rating: 84, worldCupEdition: 2022 },
  { id: 'p-seedorf', name: 'Clarence Seedorf', shortName: 'Seedorf', nickname: 'Il Professore', countryId: 'nld', position: 'MC', otherPositions: ['MCO', 'MCD'], rating: 93, worldCupEdition: 1998 },
  { id: 'p-davids', name: 'Edgar Davids', shortName: 'Davids', nickname: 'El Pitbull', countryId: 'nld', position: 'MCD', otherPositions: ['MC'], rating: 94, worldCupEdition: 1998 },
  { id: 'p-vanpersie', name: 'Robin van Persie', shortName: 'Van Persie', nickname: 'The Flying Dutchman', countryId: 'nld', position: 'DC', otherPositions: ['EI', 'SD'], rating: 94, worldCupEdition: 2014 },

  // --- BÉLGICA (bel) ---
  { id: 'p-pfaff', name: 'Jean-Marie Pfaff', shortName: 'Pfaff', nickname: 'El Simpático', countryId: 'bel', position: 'POR', otherPositions: [], rating: 93, worldCupEdition: 1986 },
  { id: 'p-scifo', name: 'Enzo Scifo', shortName: 'Scifo', nickname: 'El Pequeño Pelé', countryId: 'bel', position: 'MCO', otherPositions: ['MC'], rating: 94, worldCupEdition: 1990 },
  { id: 'p-kompany', name: 'Vincent Kompany', shortName: 'Kompany', nickname: 'Vince the Prince', countryId: 'bel', position: 'DFC', otherPositions: [], rating: 94, worldCupEdition: 2018 },
  { id: 'p-hazard', name: 'Eden Hazard', shortName: 'Hazard', nickname: 'El Duque', countryId: 'bel', position: 'EI', otherPositions: ['MCO', 'ED'], rating: 95, worldCupEdition: 2018 },
  { id: 'p-debruyne', name: 'Kevin De Bruyne', shortName: 'De Bruyne', nickname: 'The Ginger King', countryId: 'bel', position: 'MC', otherPositions: ['MCO', 'ED'], rating: 94, worldCupEdition: 2018 },
  { id: 'p-lukaku', name: 'Romelu Lukaku', shortName: 'Lukaku', nickname: 'Big Rom', countryId: 'bel', position: 'DC', otherPositions: [], rating: 89, worldCupEdition: 2018 },
  { id: 'p-courtois', name: 'Thibaut Courtois', shortName: 'Courtois', nickname: 'La Jirafa', countryId: 'bel', position: 'POR', otherPositions: [], rating: 91, worldCupEdition: 2018 },
  { id: 'p-witsel', name: 'Axel Witsel', shortName: 'Witsel', nickname: 'Chalupa', countryId: 'bel', position: 'MC', otherPositions: ['MCD', 'DFC'], rating: 86, worldCupEdition: 2018 },
  { id: 'p-castagne', name: 'Timothy Castagne', shortName: 'Castagne', nickname: 'El Belga de Acero', countryId: 'bel', position: 'LD', otherPositions: ['LI', 'CAD', 'CAI'], rating: 82, worldCupEdition: 2022 },
  { id: 'p-doku', name: 'Jérémy Doku', shortName: 'Doku', nickname: 'The Flash', countryId: 'bel', position: 'EI', otherPositions: ['ED'], rating: 86, worldCupEdition: 2022 },
  { id: 'p-wilmots', name: 'Marc Wilmots', shortName: 'Wilmots', nickname: 'Toro de Dongelberg', countryId: 'bel', position: 'MCO', otherPositions: ['DC', 'MC'], rating: 91, worldCupEdition: 2002 },
  { id: 'p-vertonghen', name: 'Jan Vertonghen', shortName: 'Vertonghen', nickname: 'Super Jan', countryId: 'bel', position: 'DFC', otherPositions: ['LI'], rating: 88, worldCupEdition: 2018 },
  { id: 'p-preudhomme', name: 'Michel Preud\'homme', shortName: 'Preud\'homme', nickname: 'San Michel', countryId: 'bel', position: 'POR', otherPositions: [], rating: 93, worldCupEdition: 1994 },

  // --- CROACIA (hrv) ---
  { id: 'p-suker', name: 'Davor Šuker', shortName: 'Šuker', nickname: 'El Mago de Osijek', countryId: 'hrv', position: 'DC', otherPositions: [], rating: 95, worldCupEdition: 1998 },
  { id: 'p-boban', name: 'Zvonimir Boban', shortName: 'Boban', nickname: 'Zorro', countryId: 'hrv', position: 'MCO', otherPositions: ['MC'], rating: 94, worldCupEdition: 1998 },
  { id: 'p-prosinecki', name: 'Robert Prosinečki', shortName: 'Prosinečki', nickname: 'Žuti (El Rubio)', countryId: 'hrv', position: 'MC', otherPositions: ['MCO'], rating: 93, worldCupEdition: 1998 },
  { id: 'p-modric', name: 'Luka Modrić', shortName: 'Modrić', nickname: 'El Póquer de Zadar', countryId: 'hrv', position: 'MC', otherPositions: ['MCO', 'MCD'], rating: 96, worldCupEdition: 2018 },
  { id: 'p-rakitic', name: 'Ivan Rakitić', shortName: 'Rakitić', nickname: 'Raketa', countryId: 'hrv', position: 'MC', otherPositions: ['MCD', 'MCO'], rating: 91, worldCupEdition: 2018 },
  { id: 'p-mandzukic', name: 'Mario Mandžukić', shortName: 'Mandžukić', nickname: 'Super Mario', countryId: 'hrv', position: 'DC', otherPositions: ['EI', 'ED'], rating: 90, worldCupEdition: 2018 },
  { id: 'p-perisic', name: 'Ivan Perišić', shortName: 'Perišić', nickname: 'El Correcaminos', countryId: 'hrv', position: 'EI', otherPositions: ['ED', 'LI', 'CAI'], rating: 88, worldCupEdition: 2018 },
  { id: 'p-gvardiol', name: 'Joško Gvardiol', shortName: 'Gvardiol', nickname: 'Pepito', countryId: 'hrv', position: 'DFC', otherPositions: ['LI'], rating: 88, worldCupEdition: 2022 },
  { id: 'p-kovacic', name: 'Mateo Kovačić', shortName: 'Kovačić', nickname: 'El Profesor', countryId: 'hrv', position: 'MC', otherPositions: ['MCD'], rating: 87, worldCupEdition: 2018 },
  { id: 'p-livakovic', name: 'Dominik Livaković', shortName: 'Livaković', nickname: 'El Pulpo de Zadar', countryId: 'hrv', position: 'POR', otherPositions: [], rating: 84, worldCupEdition: 2022 },
  { id: 'p-olic', name: 'Ivica Olić', shortName: 'Olić', nickname: 'Gato de Hierro', countryId: 'hrv', position: 'DC', otherPositions: ['EI'], rating: 89, worldCupEdition: 2014 },
  { id: 'p-srna', name: 'Darijo Srna', shortName: 'Srna', nickname: 'Icono de Metković', countryId: 'hrv', position: 'LD', otherPositions: ['ED', 'CAD'], rating: 90, worldCupEdition: 2014 },
  { id: 'p-brozovic', name: 'Marcelo Brozović', shortName: 'Brozović', nickname: 'Epic Brozo', countryId: 'hrv', position: 'MCD', otherPositions: ['MC'], rating: 88, worldCupEdition: 2018 },

  // --- MARRUECOS (mar) ---
  { id: 'p-zaki', name: 'Badou Zaki', shortName: 'Zaki', nickname: 'El León del Atlas', countryId: 'mar', position: 'POR', otherPositions: [], rating: 92, worldCupEdition: 1986 },
  { id: 'p-timoumi', name: 'Mohamed Timoumi', shortName: 'Timoumi', nickname: 'El Zurdo de Oro', countryId: 'mar', position: 'MCO', otherPositions: ['MC'], rating: 93, worldCupEdition: 1986 },
  { id: 'p-naybet', name: 'Noureddine Naybet', shortName: 'Naybet', nickname: 'El Comandante', countryId: 'mar', position: 'DFC', otherPositions: [], rating: 92, worldCupEdition: 1998 },
  { id: 'p-hadji', name: 'Mustapha Hadji', shortName: 'Hadji', nickname: 'El Mago de Atlas', countryId: 'mar', position: 'MCO', otherPositions: ['ED', 'SD'], rating: 92, worldCupEdition: 1998 },
  { id: 'p-ziyech', name: 'Hakim Ziyech', shortName: 'Ziyech', nickname: 'El Mago', countryId: 'mar', position: 'ED', otherPositions: ['MCO'], rating: 87, worldCupEdition: 2022 },
  { id: 'p-hakimi', name: 'Achraf Hakimi', shortName: 'Hakimi', nickname: 'Arraez', countryId: 'mar', position: 'LD', otherPositions: ['CAD', 'LI'], rating: 90, worldCupEdition: 2022 },
  { id: 'p-amrabat', name: 'Sofyan Amrabat', shortName: 'Amrabat', nickname: 'El Gladiador', countryId: 'mar', position: 'MCD', otherPositions: ['MC'], rating: 84, worldCupEdition: 2022 },
  { id: 'p-ennesyri', name: 'Youssef En-Nesyri', shortName: 'En-Nesyri', nickname: 'El Avión', countryId: 'mar', position: 'DC', otherPositions: [], rating: 84, worldCupEdition: 2022 },
  { id: 'p-bounou', name: 'Yassine Bounou', shortName: 'Bono', nickname: 'Bono', countryId: 'mar', position: 'POR', otherPositions: [], rating: 88, worldCupEdition: 2022 },
  { id: 'p-aguerd', name: 'Nayef Aguerd', shortName: 'Aguerd', nickname: 'El Muro', countryId: 'mar', position: 'DFC', otherPositions: [], rating: 84, worldCupEdition: 2022 },
  { id: 'p-bouderbala', name: 'Aziz Bouderbala', shortName: 'Bouderbala', nickname: 'El Regateador', countryId: 'mar', position: 'ED', otherPositions: ['MCO'], rating: 91, worldCupEdition: 1986 },
  { id: 'p-saiss', name: 'Romain Saïss', shortName: 'Saïss', nickname: 'El Capitán', countryId: 'mar', position: 'DFC', otherPositions: ['MCD'], rating: 86, worldCupEdition: 2022 },
  { id: 'p-ounahi', name: 'Azzedine Ounahi', shortName: 'Ounahi', nickname: 'El Estudiante', countryId: 'mar', position: 'MC', otherPositions: ['MCO'], rating: 85, worldCupEdition: 2022 }
];

/**
 * Función utilitaria de acceso rápido para filtrar jugadores por país y posición.
 * Minimiza la carga de procesamiento en componentes visuales ("use client").
 */
export function getPlayersByCountryAndPosition(countryId: string, position: Position | string): Player[] {
  return playersData.filter(
    (player) => player.countryId === countryId && (player.position === position || player.otherPositions.includes(position))
  );
}